### ISSUE TITLE
uncaughtException: Cannot set properties of undefined (setting 'path')

### ISSUE THREAD

**Issue by mathcoll** [apidoc/apidoc#1128]
# Describe the bug
Using apidoc v0.50.3 I got the following error :
```
verbose: Writing files...
verbose: Copying template index.html to: /home/username/doc/docs/
verbose: Copying fonts to: /home/username/doc/docs/assets
verbose: Copying bootstrap css to: /home/username/doc/docs/assets
verbose: Copying prism css to: /home/username/doc/docs/assets
verbose: Copying main css to: /home/username/doc/docs/assets
verbose: Running webpack bundler
Sun, 26 Dec 2021 15:03:28 GMT uncaughtException: Cannot set properties of undefined (setting 'path')
TypeError: Cannot set properties of undefined (setting 'path')
    at /home/mathieu/.nvm/versions/node/v17.3.0/lib/node_modules/apidoc/lib/writer.js:97:33
    at new Promise (<anonymous>)
    at Writer.runWebpack (/home/mathieu/.nvm/versions/node/v17.3.0/lib/node_modules/apidoc/lib/writer.js:92:12)
    at Writer.createOutputFiles (/home/mathieu/.nvm/versions/node/v17.3.0/lib/node_modules/apidoc/lib/writer.js:84:17)
    at Writer.write (/home/mathieu/.nvm/versions/node/v17.3.0/lib/node_modules/apidoc/lib/writer.js:34:17)
    at Object.createDoc (/home/mathieu/.nvm/versions/node/v17.3.0/lib/node_modules/apidoc/lib/index.js:93:12)
    at Object.<anonymous> (/home/mathieu/.nvm/versions/node/v17.3.0/lib/node_modules/apidoc/bin/apidoc:170:12)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
```

# Steps to reproduce
```
#!/bin/bash
apidoc \
	-i /home/username/src \
	-f file1.js \
	-f file2.js \
	-o /home/username/doc/docs/ \
	--template /username/doc/templatev4/ \
	--config /home/username/apidoc.json \
	-v \
	-d
```

# Information
- Version of apidoc: 0.50.3 
- Operating system (e.g. GNU+Linux/MacOS/Windows): `Linux bleu 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Node version: v17.3.0
- Browser (e.g. firefox, chrome): we don't care :-)

**Comment by NicolasCARPi** [comment]
You are using a custom template, right? Does it work with the default template? What is in your config file? The error seems to indicate that webpack could not be found/required, is it present?

**Comment by mathcoll** [comment]
Thank you for your feedback.
I had to reinstall both `npm install esbuild-loader webpack`
And then I used the repository template : it works fine.
So there still have something weird in my custom template. I'll investigate myself later. :-)
