### ISSUE TITLE
Example boxes looks gray and unreadable

### ISSUE THREAD

**Issue by andres15alvarez** [apidoc/apidoc#1170]
When I generate the documentation all example boxes looks gray, does not looks like the examples with black background and colorized.

![Captura de pantalla de 2022-02-18 10-05-43](https://user-images.githubusercontent.com/9939646/154697500-51582831-3c45-4f11-ad14-f10c98e4f4c0.png)

My apidoc.json:
```
{
  "name": "API documentation",
  "version": "0.3.0",
  "description": "Documentation for the endpoint of",
  "title": "Documentation",
  "url" : "https://github.com",
  "sampleUrl": "https://github.com",
  "output": "/tmp/apidoc-output",
  "input": [
    "example"
  ],
  "header": {
    "title": "Introduction",
    "filename": "header.md"
  },
  "footer": {
    "title": "Best practices",
    "filename": "footer.md"
  },
  "template": {
    "withCompare": true,
    "withGenerator": true,
    "aloneDisplay": false
  }
}
```

Example of documentation:
```python
"""
   @api {post} v2/dlocal/user/:uuid4/account/otp Send
   @apiName Send
   @apiGroup Dlocal OTP
   @apiVersion  2.0.0
   @apiDescription On this endpoint you can send the otp for email and phone.

   @apiHeader {String} Authorization='Bearer 123456789asdfghjklzx456fgyhj654'
   @apiParam  {String} uuid4 UUID4 identifier of the user.
   
   @apiBody {String="EMAIL","PHONE"} type Type of the OTP.
   @apiBody {String} code OTP code to validate. Max length of 6.
   
   @apiParamExample  {json} Request-Example:
   {
       "type": "EMAIL",
       "code": "111111"
   }
   
   @apiSuccessExample {json} Success-Response:
   HTTP/1.1 200 OK
   {
      "account_id": "ISGA-50309-e34c8c1278db487ea9296053646ff7d1",
      "type": "EMAIL",
      "status": "WAITING_FOR_OTP_PHONE",
      "status_code": "202",
      "status_detail": "OTP PHONE is required."
   }
"""
```

# Information

- Version of apidoc: 0.50.4
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 20.04
- Node version: v16.13.2
- Browser (e.g. firefox, chrome): Brave, Firefox, Chrome

**Comment by NicolasCARPi** [comment]
Hello,

First, generate the doc with the `-d` flag to see any error, weird stuff in the logs. Second, check your browser console for issues. Third refresh the page without cache.

**Comment by andres15alvarez** [comment]
The logs do not have any error.
Here is the console with some issues:
![Captura de pantalla de 2022-02-18 10-39-47](https://user-images.githubusercontent.com/9939646/154704190-45448a05-2577-4218-bbe0-1c55518aaebd.png)
After refreshing the page without cache raise the same issues.

**Comment by andres15alvarez** [comment]
```python
"""
        @api {delete} /v2/alliance/:uuid4 Delete an alliance given its uuid4.
        @apiName Delete alliance.
        @apiGroup Alliance
        @apiVersion  2.0.0
        
        
        @apiSuccessExample {Obj} Success-Response:
        {
            "data": "Alliance 5543446c-700c-46ee-a464-e4c9d2a621d4 deleted",
            "status": "ok"
        }
    """
```

**Comment by NicolasCARPi** [comment]
Change `apiName` to `DeleteAlliance`. `apiName` have to be like that, not with space or punctuation. The documentation should be changed to reflect that need.

Also, you can change the `Obj` to `json` to get better syntax highlighting.

**Comment by andres15alvarez** [comment]
I made the changes:

**Comment by andres15alvarez** [comment]
I made the changes:
```python
    """
        @api {delete} /v2/alliance/:uuid4 Delete
        @apiName DeleteAlliance
        @apiGroup Alliance
        @apiVersion  2.0.0
        
        
        @apiSuccessExample {json} Success-Response:
        {
            "data": "Alliance 5543446c-700c-46ee-a464-e4c9d2a621d4 deleted",
            "status": "ok"
        }
    """
```
But the examples still looks gray:
![Captura de pantalla de 2022-02-18 11-33-42](https://user-images.githubusercontent.com/9939646/154713141-6e389443-fa2d-46c6-b95b-33e807a81bb2.png)

**Comment by NicolasCARPi** [comment]
Refresh the cache!

**Comment by jerrens** [comment]
@NicolasCARPi I encountered this problem too when I tried the suggestion in https://github.com/apidoc/apidoc/issues/321.

In my `footer.md` file, I had the following line:

Originally:
```md
# Best Practices

## API Tokens
```
Result: Examples look good; only see 'Best Practices' in the left nav bar

Add Span element per https://github.com/apidoc/apidoc/issues/321 with 'api-' prefix
```md
# Best Practices

## <span id="api-footer-token-details">API Tokens</span>
```
Result: Examples still look good; still only see 'Best Practices' in the left nav bar


Add Anchor between Span and header text
```md
# Best Practices

## <span id="api-footer-token-details"><a name="APITokens"></a>API Tokens</span>
```
Result: 
* Now see 'API Tokens' as a child under 'Best Practices' in the left nav bar
* Hyperlink for 'API Tokens' shows as: "/index.html#api-footer-token-details%22%3E%3Ca%20name=%22APITokens"
* Have the following errors in the console
```
main.bundle.js:60 Uncaught Error: Syntax error, unrecognized expression: #api-footer-token-details"><a name="APITokens
    at be.error (main.bundle.js:60:10014)
    at be.tokenize (main.bundle.js:60:16199)
    at be.select (main.bundle.js:60:19369)
    at Function.be [as find] (main.bundle.js:60:3372)
    at n.fn.init.find (main.bundle.js:63:2853)
    at new n.fn.init (main.bundle.js:60:44138)
    at D (main.bundle.js:60:39627)
    at HTMLAnchorElement.<anonymous> (main.bundle.js:1:5118)
    at main.bundle.js:60:40012
    at Function.map (main.bundle.js:60:41985)
be.error @ main.bundle.js:60
be.tokenize @ main.bundle.js:60
be.select @ main.bundle.js:60
be @ main.bundle.js:60
find @ main.bundle.js:63
n.fn.init @ main.bundle.js:60
D @ main.bundle.js:60
(anonymous) @ main.bundle.js:1
(anonymous) @ main.bundle.js:60
map @ main.bundle.js:60
map @ main.bundle.js:60
E.refresh @ main.bundle.js:1
E @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
each @ main.bundle.js:60
each @ main.bundle.js:60
o @ main.bundle.js:1
Ue @ main.bundle.js:370
(anonymous) @ main.bundle.js:98
main.bundle.js:98 [Violation] 'DOMContentLoaded' handler took 198ms
main.bundle.js:60 Uncaught Error: Syntax error, unrecognized expression: #api-footer-token-details"><a name="APITokens
    at be.error (main.bundle.js:60:10014)
    at be.tokenize (main.bundle.js:60:16199)
    at be.select (main.bundle.js:60:19369)
    at Function.be [as find] (main.bundle.js:60:3372)
    at n.fn.init.find (main.bundle.js:63:2853)
    at new n.fn.init (main.bundle.js:60:44138)
    at D (main.bundle.js:60:39627)
    at HTMLAnchorElement.<anonymous> (main.bundle.js:1:5118)
    at main.bundle.js:60:40012
    at Function.map (main.bundle.js:60:41985)
be.error @ main.bundle.js:60
be.tokenize @ main.bundle.js:60
be.select @ main.bundle.js:60
be @ main.bundle.js:60
find @ main.bundle.js:63
n.fn.init @ main.bundle.js:60
D @ main.bundle.js:60
(anonymous) @ main.bundle.js:1
(anonymous) @ main.bundle.js:60
map @ main.bundle.js:60
map @ main.bundle.js:60
E.refresh @ main.bundle.js:1
E @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
each @ main.bundle.js:60
each @ main.bundle.js:60
o @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
each @ main.bundle.js:60
each @ main.bundle.js:60
(anonymous) @ main.bundle.js:1
dispatch @ main.bundle.js:61
ie.handle @ main.bundle.js:61
load (async)
add @ main.bundle.js:61
(anonymous) @ main.bundle.js:61
each @ main.bundle.js:60
each @ main.bundle.js:60
T @ main.bundle.js:61
on @ main.bundle.js:61
(anonymous) @ main.bundle.js:1
3497 @ main.bundle.js:1
rt @ main.bundle.js:97
(anonymous) @ main.bundle.js:97
(anonymous) @ main.bundle.js:370
(anonymous) @ main.bundle.js:370
[Violation] Forced reflow while executing JavaScript took 60ms
```

**Comment by NicolasCARPi** [comment]
That error message is helpful. I don't have the bandwidth to investigate the issue though.

**Comment by jybleau** [comment]
FTR
I fix the same problem by fixing the `unrecognized expression` error message. 

I had this parameter: `@apiGroup Organization's Group` which caused the error.

I removed the apostrophe: `@apiGroup Organization Group` and it fixed the expresson error and the color issue.
