### ISSUE TITLE
Apidoc content security block issue using express typescript starter

### ISSUE THREAD

**Issue by rwsabhishek** [apidoc/apidoc#1237]
# Describe the bug
Hello,
I have integrated apidoc in node  express using typescript-express-starter.
https://www.npmjs.com/package/typescript-express-starter

When i up the server using ts-node and try to access apidoc.I get blank screen and get below error in console-
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at n.Function (<anonymous>)
    at n.createFunctionContext (main.bundle.js:41:1515)
    at n.compile (main.bundle.js:41:57)
    at n.compileChildren (main.bundle.js:50:5580)
    at n.compile (main.bundle.js:38:18989)
    at n.compileChildren (main.bundle.js:50:5580)
    at n.compile (main.bundle.js:38:18989)
    at n.compileChildren (main.bundle.js:50:5580)
    at n.compile (main.bundle.js:38:18989)
    at n.compileChildren (main.bundle.js:50:5580)  
 

# Information

- Version of apidoc:latest
- Operating system Windows
- Node version:16
- Browser (e.g. firefox, chrome):chrome
![image](https://user-images.githubusercontent.com/107095684/172537292-1b02f287-121f-4dc3-b32d-a978dd2af9ca.png)

**Comment by NicolasCARPi** [comment]
Currently apidoc doesn't work with strict CSP because of handlebars usage.
