### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by yuyang8** [apidoc/apidoc#1257]
In Windows 7  CMD, run  apidoc, we have something wrong as below.  node is v12.22.7: 
const title = projectInfo.title ?? projectInfo.name ?? 'Loading...';
                                              ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\yuyang8\AppData\Roaming\npm\node_modules\apidoc\lib\index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by NicolasCARPi** [comment]
Update your node version.
