### ISSUE TITLE
sending a sample request

### ISSUE THREAD

**Issue by jabr9983** [apidoc/apidoc#287]
I have been working on documenting my api and when I try to send a sample request I get this error: Error 400: Bad Request
Error: Bad Request
    at Object.exports.error (/Users/macbook-braucj/TodoMain/node_modules/express/node_modules/connect/lib/utils.js:42:13)
    at IncomingMessage. (/Users/macbook-braucj/TodoMain/node_modules/express/node_modules/connect/lib/middleware/json.js:57:73)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

I enabled cors and that allowed me to get at least to the error but I'm not exactly sure how to interpret this error. Any help would be appreciated.

**Comment by ebuildy** [comment]
Looks like a 400 HTTP error from your API server. Can you check the console?

**Comment by jabr9983** [comment]
Yea I will just have to get the server started thanks.

**Comment by jabr9983** [comment]
OPTIONS /tasks 404 1ms

This is what my console is returning. I'm not exactly sure why it is using options rather than get.

**Comment by ebuildy** [comment]
Yes this is how CORS work:

http://www.eriwen.com/javascript/how-to-cors/

![CORS HTTP workflow]
(http://b3.ms/r5KBn43zAo4j)
