### ISSUE TITLE
@apiVersion invalid

### ISSUE THREAD

**Issue by onsails** [apidoc/apidoc#3]
Hello,
I created file with api descrption:

```
  /**
   * @api {post} /api/v1/gifts Send gift to moderator
   * @apiName CreateGift
   * @apiGroup Gift
   * @apiVersion 1.0
   * @apiParam {uuid} uuid Gift's id in sandbox
   * @apiSuccessExample Success-Response:
   * HTTP/1.1 200 OK
   */
```

and package.json:

```
{
    "name": "Gifts API Doc",
    "version": "1.0",
    "description": "An api doc for gifts managing"
}
```

When I try to generate docs I get an error:

```
apidoc: Error: "@apiVersion" in file "app/controllers/api/v1/Gifts.scala" block number 1 version "1.0" not valid.
    at Parser._parseBlockElements (/usr/local/lib/node_modules/apidoc/lib/parser.js:120:12)
    at Parser.parseFile (/usr/local/lib/node_modules/apidoc/lib/parser.js:85:14)
    at main (/usr/local/lib/node_modules/apidoc/lib/apidoc.js:282:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/apidoc/bin/apidoc:126:25)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

What I did wrong?

**Comment by sgpinkus** [comment]
Should just allow any version string an warn loady about compliance with semver. Example, sometimes you don't know what the version will be, it's just "latest" but you still wanna generate updated doc.
