### ISSUE TITLE
Can not read:

### ISSUE THREAD

**Issue by Laro88** [apidoc/apidoc#447]
I am stuck after having tried almost any imaginable combination.
There is an apidoc.json in the root with hust title, url and description, should be trivial. json is verified.
I am on W7 btw.
--debug dump included.

C:\N\u320683\publicapi.git\publicapi\publicapi>apidoc --debug
debug: read: package.json
error: Can not read: apidoc.json, please check the format (e.g. missing comma).
debug: Error: Can not read: apidoc.json, please check the format (e.g. missing c
omma).
    at PackageInfo._readPackageData (C:\Users\u320683\AppData\Roaming\npm\node_m
odules\apidoc\lib\package_info.js:78:19)
    at PackageInfo.get (C:\Users\u320683\AppData\Roaming\npm\node_modules\apidoc
\lib\package_info.js:36:27)
    at Object.createDoc (C:\Users\u320683\AppData\Roaming\npm\node_modules\apido
c\lib\index.js:109:44)
    at Object.<anonymous> (C:\Users\u320683\AppData\Roaming\npm\node_modules\api
doc\bin\apidoc:107:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)

C:\N\u320683\publicapi.git\publicapi\publicapi>

**Comment by rottmann** [comment]
Can you post you package.json / apidoc.json

**Comment by Laro88** [comment]
Sure, much appreciated.
```
{
  "name": "publicapi",
  "version": "0.0.4",
  "description": "publicapi",
  "main": "app.js",
  "author": {
    "email": "laro88@nowhere.com",
    "name": "laro88"
  },
  "dependencies": {
    "apiwsbackend": "git+http://anonymous@dkdn01as686/Bonobo.Git.Server/apiwsbackend.git",
    "async": "^2.0.0-rc.2",
    "config": "^1.19.0",
    "log4js": "^0.6.33",
    "restify": "^4.0.4"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-things": "^0.2.0",
    "express-generator": "4.13.1",
    "mocha": "^2.4.5"
  }
}
```
and
```
{
    "title": "myapp API",
    "url": "http://api.myapp.com/explorer",
    "description": "Documentation for myapp API endpoints"
}
```

**Comment by rottmann** [comment]
Copy and paste your data and it work for me. Can you check file permissions, or run `npm outdated`, if without error your package.json is ok.
