### ISSUE TITLE
EACCES: permission denied, scandir (version 0.16.1)

### ISSUE THREAD

**Issue by jamtat** [apidoc/apidoc#519]
apidoc appears to try and search parent directories for something, throwing an unhandled error if it doesn't have permission to access the directory.

trace:
`debug: read: package.json
debug: read: apidoc.json
debug: read header file: api/doc/header.md
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.16.1
verbose: apidoc-core version: 0.7.1
verbose: apidoc-spec version: 0.2.0
error: EACCES: permission denied, scandir '/var/lib/openshift'
debug: Error: EACCES: permission denied, scandir '/var/lib/openshift'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at GlobSync._readdir (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/node_modules/glob/sync.js:276:41)
    at GlobSync._processReaddir (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/node_modules/glob/sync.js:136:22)
    at GlobSync._process (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/node_modules/glob/sync.js:131:10)
    at new GlobSync (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/node_modules/glob/sync.js:47:10)
    at Function.globSync [as sync] (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/node_modules/glob/sync.js:25:10)
    at PluginLoader.detectPugins (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/lib/plugin_loader.js:47:24)
    at PluginLoader.detectPugins (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/lib/plugin_loader.js:52:21)
    at PluginLoader.detectPugins (/var/lib/openshift/[app_id]/app-root/runtime/repo/node_modules/apidoc-core/lib/plugin_loader.js:52:21)`

**Comment by jamtat** [comment]
Looks like this can be fixed by adjusting detectPlugins in lib/plugin_loader.js from apidoc-core to check for permissions before accessing a directory

**Comment by rottmann** [comment]
Fixed in 0.17
