### ISSUE TITLE
Generated docs not working: "Uncaught TypeError: Invalid Version: ..."

### ISSUE THREAD

**Issue by muhlegg** [apidoc/apidoc#555]
Have used apidoc in several project before but now when I added it to a new project I cant get it to work. It generated the docs but the actual docs crashes with the following console output: 

```
8240296:1 Uncaught TypeError: Invalid Version: 
    at new K (file:///project-xxx//public/docs/api/vendor/semver.min.js?v=1480498240296:1:2607)
    at ir (file:///project-xxx//public/docs/api/vendor/semver.min.js?v=1480498240296:1:6157)
    at Array.sort (native)
    at file:///project-xxx//public/docs/api/main.js:162:17
    at Object.execCb (file:///project-xxx//public/docs/api/vendor/require.min.js:29:311)
    at Z.check (file:///project-xxx//public/docs/api/vendor/require.min.js:18:423)
    at Z.<anonymous> (file:///project-xxx//public/docs/api/vendor/require.min.js:23:9)
    at file:///project-xxx//public/docs/api/vendor/require.min.js:8:102
    at file:///project-xxx//public/docs/api/vendor/require.min.js:23:369
    at v (file:///project-xxx//public/docs/api/vendor/require.min.js:7:173)
    at Z.emit (file:///project-xxx//public/docs/api/vendor/require.min.js:23:340)
```

Any ideas why its crashing?

**Comment by rottmann** [comment]
What kind of versioning system you use? Semver? Schema: 1.0.0, 1.47.11, ...
apiDoc uses Semver http://semver.org/

**Comment by muhlegg** [comment]
I do not actually have any versions defined in my current api docs definitions.

**Comment by rottmann** [comment]
Can you post the generated api_project.json

**Comment by muhlegg** [comment]
```
{
  "name": "xxx API Documentation",
  "version": "",
  "description": "",
  "title": "xxx API Docs",
  "url": "xxx.dev/api",
  "sampleUrl": false,
  "apidoc": "0.2.0",
  "generator": {
    "name": "apidoc",
    "time": "2016-11-30T09:49:16.909Z",
    "url": "http://apidocjs.com",
    "version": "0.16.1"
  }
}
```

**Comment by rottmann** [comment]
Somewhere in your source must be a version string that is not semver compliant, but in this case an Error should be thrown when you generate the docs. Can you PM me the generated files?

**Comment by muhlegg** [comment]
Quite a lot of confidential stuff in the docs so I'd rather not send the whole package. Rolled back to 0.12.3 version where it still worked without version numbers defined..

**Comment by NicolasCARPi** [comment]
Please reopen issue if problem is still present.
