### ISSUE TITLE
Error js in browser. Invalid Version: 1

### ISSUE THREAD

**Issue by Neli-Taylor** [apidoc/apidoc#706]
Hi.
I copy http://apidocjs.com/source/example_basic/example.js and run `apidoc`
and have error in chrome!

```
TypeError: Invalid Version: 1
    at new K (file:///D:/Nghi/newsystem/apidoc/vendor/semver.min.js?v=1518086892747:1:2607)
    at ir (file:///D:/Nghi/newsystem/apidoc/vendor/semver.min.js?v=1518086892747:1:6157)
    at Array.sort (native)
    at file:///D:/Nghi/newsystem/apidoc/main.js:164:17
    at Object.execCb (file:///D:/Nghi/newsystem/apidoc/vendor/require.min.js:30:208)
    at ea.check (file:///D:/Nghi/newsystem/apidoc/vendor/require.min.js:18:422)
    at ea.<anonymous> (file:///D:/Nghi/newsystem/apidoc/vendor/require.min.js:23:282)
    at file:///D:/Nghi/newsystem/apidoc/vendor/require.min.js:8:101
    at file:///D:/Nghi/newsystem/apidoc/vendor/require.min.js:24:199
    at x (file:///D:/Nghi/newsystem/apidoc/vendor/require.min.js:7:173)
```

**Comment by ziv** [comment]
The same here. On project that produced before working doc's but suddenly stopped.
Reproduced on chrome and firefox.

Error:
`require.min.js:19 TypeError: Invalid Version: 1
    at new K (semver.min.js?v=1525780965285:1)
    at ir (semver.min.js?v=1525780965285:1)
    at Array.sort (native)
    at main.js:164
    at Object.execCb (require.min.js:30)
    at ea.check (require.min.js:18)
    at ea.<anonymous> (require.min.js:23)
    at require.min.js:8
    at require.min.js:24
    at x (require.min.js:7)
check @ require.min.js:19`

packages.json:
`  "dependencies": {
    "agenda": "^0.9.1",
    "aws-sdk": "^2.48.0",
    "body-parser": "^1.17.1",
    "bufferutil": "^3.0.2",
    "chalk": "^2.3.0",
    "colors": "^1.1.2",
    "commander": "^2.12.2",
    "compression": "^1.6.2",
    "config": "^1.26.1",
    "cookie-parser": "^1.4.3",
    "csv-parse": "^2.0.0",
    "datalib": "^1.7.3",
    "debug": "^2.6.6",
    "dnode": "^1.2.2",
    "dot-object": "^1.7.0",
    "dot-prop-immutable": "^1.4.0",
    "express": "^4.15.2",
    "express-session": "^1.15.2",
    "express-validator": "^5.1.2",
    "express-ws": "^3.0.0",
    "fs-extra": "^5.0.0",
    "glob": "^7.1.2",
    "inquirer": "^3.0.6",
    "lodash": "^4.17.4",
    "material-design-icons": "^3.0.1",
    "mocha": "^3.5.3",
    "mocha-junit-reporter": "^1.17.0",
    "mockgoose": "^7.3.5",
    "moment": "^2.18.1",
    "moment-strftime": "^0.2.2",
    "mongoose": "^5.0.10",
    "morgan": "^1.8.1",
    "multer": "^1.3.0",
    "node-ipc": "^9.1.0",
    "pty.js": "^0.3.1",
    "querymen": "^2.1.3",
    "request-promise-native": "^1.0.5",
    "rxjs": "^5.3.1",
    "table": "^4.0.2",
    "utf-8-validate": "^3.0.3",
    "uuid": "^3.0.1",
    "vorpal": "^1.12.0",
    "winston": "^2.3.1",
    "winston-mongodb": "^2.0.10",
    "ws": "^3.0.0"
  },
  "devDependencies": {
    "agendash": "^0.4.0",
    "apidoc": "^0.17.5",
    "chai": "^3.5.0",
    "eslint": "^4.18.2",
    "json5": "^0.5.1",
    "nyc": "^11.2.1",
    "sinon": "^4.5.0",
    "supertest": "^3.0.0"
  }`

**Comment by NicolasCARPi** [comment]
Works now.
