### ISSUE TITLE
Missing environment.conf

### ISSUE THREAD

**Issue by huseyinkozan** [apidoc/apidoc#777]
Hi,

While using apidoc in Toradex yocto environment I got error below. It was not there until a few days before.
```bash
# root @ e560 in /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0 [12:25:30] C:1
$ apidoc -c ${WORKDIR}/apidoc.json -i ${WORKDIR} -f "api.js" -o ${WORKDIR}/public/api/
{"message":"ENOENT: no such file or directory, stat '/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/99-environment.conf'","level":"error"}

$ echo ${WORKDIR}
/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0
```

Checking the file:
```bash
$ ll /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/99-environment.conf
lrwxrwxrwx 1 hk hk 24 Mar 14 15:19 /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/99-environment.conf -> ../../../etc/environment

$ LC_ALL=C ll /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/../../../etc/environment
ls: cannot access '/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/../../../etc/environment': No such file or directory
```

Searched but couldnt find which bitbake package provides /etc/environment. 

How can I solve this problem ?

**Comment by huseyinkozan** [comment]
Forgot to include verbose and debug args. Added output below.
```bash
$ apidoc -c ${WORKDIR}/apidoc.json -i ${WORKDIR} -f "api.js" -o ${WORKDIR}/public/api/ -v        
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.17.7","level":"verbose"}
{"message":"apidoc-core version: 0.8.3","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}
{"message":"run parser","level":"verbose"}
{"message":"ENOENT: no such file or directory, stat '/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/99-environment.conf'","level":"error"}

# root @ e560 in /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0 [12:35:07] C:1
$ apidoc -c ${WORKDIR}/apidoc.json -i ${WORKDIR} -f "api.js" -o ${WORKDIR}/public/api/ -v --debug
{"message":"read: /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/package.json","level":"debug"}
{"message":"read: /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/apidoc.json","level":"debug"}
{"message":"read header file: /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/api-header.md","level":"debug"}
{"message":"read header file: /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/api-footer.md","level":"debug"}
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.17.7","level":"verbose"}
{"message":"apidoc-core version: 0.8.3","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}
{"message":"No plugins found.","level":"debug"}
{"message":"load parser language: .clj, ./languages/clj.js","level":"debug"}
{"message":"load parser language: .coffee, ./languages/coffee.js","level":"debug"}
{"message":"load parser language: .erl, ./languages/erl.js","level":"debug"}
{"message":"load parser language: .ex, ./languages/ex.js","level":"debug"}
{"message":"load parser language: .exs, ./languages/ex.js","level":"debug"}
{"message":"load parser language: .litcoffee, ./languages/coffee.js","level":"debug"}
{"message":"load parser language: .lua, ./languages/lua.js","level":"debug"}
{"message":"load parser language: .pl, ./languages/pm.js","level":"debug"}
{"message":"load parser language: .pm, ./languages/pm.js","level":"debug"}
{"message":"load parser language: .py, ./languages/py.js","level":"debug"}
{"message":"load parser language: .rb, ./languages/rb.js","level":"debug"}
{"message":"load parser language: default, ./languages/default.js","level":"debug"}
{"message":"load parser: api, ./parsers/api.js","level":"debug"}
{"message":"load parser: apidefine, ./parsers/api_define.js","level":"debug"}
{"message":"load parser: apidescription, ./parsers/api_description.js","level":"debug"}
{"message":"load parser: apierror, ./parsers/api_error.js","level":"debug"}
{"message":"load parser: apierrorexample, ./parsers/api_error_example.js","level":"debug"}
{"message":"load parser: apiexample, ./parsers/api_example.js","level":"debug"}
{"message":"load parser: apiheader, ./parsers/api_header.js","level":"debug"}
{"message":"load parser: apiheaderexample, ./parsers/api_header_example.js","level":"debug"}
{"message":"load parser: apigroup, ./parsers/api_group.js","level":"debug"}
{"message":"load parser: apiname, ./parsers/api_name.js","level":"debug"}
{"message":"load parser: apiparam, ./parsers/api_param.js","level":"debug"}
{"message":"load parser: apiparamexample, ./parsers/api_param_example.js","level":"debug"}
{"message":"load parser: apipermission, ./parsers/api_permission.js","level":"debug"}
{"message":"load parser: apisuccess, ./parsers/api_success.js","level":"debug"}
{"message":"load parser: apisuccessexample, ./parsers/api_success_example.js","level":"debug"}
{"message":"load parser: apiuse, ./parsers/api_use.js","level":"debug"}
{"message":"load parser: apiversion, ./parsers/api_version.js","level":"debug"}
{"message":"load parser: apisamplerequest, ./parsers/api_sample_request.js","level":"debug"}
{"message":"load parser: apideprecated, ./parsers/api_deprecated.js","level":"debug"}
{"message":"load worker: apierrorstructure, ./workers/api_error_structure.js","level":"debug"}
{"message":"load worker: apierrortitle, ./workers/api_error_title.js","level":"debug"}
{"message":"load worker: apigroup, ./workers/api_group.js","level":"debug"}
{"message":"load worker: apiheaderstructure, ./workers/api_header_structure.js","level":"debug"}
{"message":"load worker: apiheadertitle, ./workers/api_header_title.js","level":"debug"}
{"message":"load worker: apiname, ./workers/api_name.js","level":"debug"}
{"message":"load worker: apiparamtitle, ./workers/api_param_title.js","level":"debug"}
{"message":"load worker: apipermission, ./workers/api_permission.js","level":"debug"}
{"message":"load worker: apisamplerequest, ./workers/api_sample_request.js","level":"debug"}
{"message":"load worker: apistructure, ./workers/api_structure.js","level":"debug"}
{"message":"load worker: apisuccessstructure, ./workers/api_success_structure.js","level":"debug"}
{"message":"load worker: apisuccesstitle, ./workers/api_success_title.js","level":"debug"}
{"message":"load worker: apiuse, ./workers/api_use.js","level":"debug"}
{"message":"load filter: apierror, ./filters/api_error.js","level":"debug"}
{"message":"load filter: apiheader, ./filters/api_header.js","level":"debug"}
{"message":"load filter: apiparam, ./filters/api_param.js","level":"debug"}
{"message":"load filter: apisuccess, ./filters/api_success.js","level":"debug"}
{"message":"run parser","level":"verbose"}
{"message":"ENOENT: no such file or directory, stat '/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/99-environment.conf'","level":"error"}
{"message":"Error: ENOENT: no such file or directory, stat '/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot/usr/lib/environment.d/99-environment.conf'\n    at Object.statSync (fs.js:851:3)\n    at Object.statSync (/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/node_modules/graceful-fs/polyfills.js:295:24)\n    at /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/node_modules/apidoc-core/lib/utils/find_files.js:86:14\n    at Array.filter (<anonymous>)\n    at FindFiles.search (/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/node_modules/apidoc-core/lib/utils/find_files.js:84:19)\n    at Parser.parseFiles (/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/node_modules/apidoc-core/lib/parser.js:91:27)\n    at /opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/node_modules/apidoc-core/lib/index.js:213:24\n    at Array.forEach (<anonymous>)\n    at Object.parse (/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/node_modules/apidoc-core/lib/index.js:208:25)\n    at Object.createDoc (/opt/yocto/build/tmp-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/nodeapp/1.0.0-r0/recipe-sysroot-native/usr/lib/node_modules/apidoc/lib/index.js:113:22)","level":"debug"}
```

**Comment by NicolasCARPi** [comment]
Hello,

Closing this issue for inactivity and because it's much too specific and might not be a problem of apidoc.
