### ISSUE TITLE
apidoc cannot be used after Linux is installed

### ISSUE THREAD

**Issue by nicolaslh** [apidoc/apidoc#890]
The error will appear after running apidoc, is there any way to solve it

/usr/lib/node_modules/apidoc/node_modules/chokidar/index.js:151
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/apidoc/node_modules/nodemon/lib/monitor/watch.js:6:16)

**Comment by Stephanzion** [comment]
Did you solve the problem? Got just the same

**Comment by NicolasCARPi** [comment]
First, it's a bad idea to install npm packages with root permissions. Second, you're not providing enough info on your operating system, npm version, apidoc version or commands to reproduce the issue.
